version: '2.4'
services:

  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    env_file:
      - .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  swagger:
    image: swaggerapi/swagger-ui:v3.25.0
    container_name: swagger
    restart: always
    env_file: .env
    ports:
      - 9999:8080

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    restart: always
    ports:
      - 9998:8080
      