// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package entity

import mock "github.com/stretchr/testify/mock"

// MockEntity is an autogenerated mock type for the Entity type
type MockEntity struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *MockEntity) GetID() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
